//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public enum EAction
	{
		MoveUP,
		MoveLEFT,
		MoveDOWN,
		MoveRIGHT,
		HUG,
		NONE
	}

	public enum EDirection
	{
		UP,
		LEFT,
		DOWN,
		RIGHT
	}

	public enum EGameMode
	{
		SP,
		MP
	}

	public enum EGryll
	{
		WINSTON,
		ACB,
		BEARD
	}

	public enum ERotation
	{
		CW0,
		CW90,
		CW180,
		CW270
	}

	public class HelperFunctions
	{
		public static EDirection GetDirection(int index)
		{
			switch (index)
			{
			case 0:
				return EDirection.UP;
			case 1:
				return EDirection.LEFT;
			case 2:
				return EDirection.DOWN;
			case 3:
				return EDirection.RIGHT;
			}
			return EDirection.UP;
		}
	}
}

